### PR TITLE
support json response as cli output

### PR DESCRIPTION
**Pull request by Yuni-sa**
to solve #35 
@yonahd

### CODE REVIEW

**Comment by Yuni-sa** [comment]
only problem i've noticed when testing is that the json output for hpas is different when no unused hpas are found because of a difference in the JSON functions.

output for no unused hpas is: 
```json
{}
```

all other resources when there none unused return something like: 
```json
{
  "kor": {
    "Deployments": null
  }
}
```

refactoring the json outputs to one standard should probably be discussed in a different issue.

**Comment by Yuni-sa** [comment]
> refactoring the json outputs to one standard should probably be discussed in a different issue.

also some returning null and some returning an empty array:
```json
{
  "default": {
    "ConfigMap": [],
    "Deployment": null,
    "Hpa": null,
    "Ingress": [],
    "Pvc": [],
    "Role": [],
    "Secret": [],
    "Service": null,
    "ServiceAccount": [],
    "Statefulset": null
  }
}
```

**Comment by Yuni-sa** [comment]
I can also add `fmt.Fprintf(os.Stderr, "Failed to process namespace %s: %v\n", namespace, err)` to the cmd functions for better formatting.
@yonahd update me on what you think.

**Comment by yonahd** [comment]
> only problem i've noticed when testing is that the json output for hpas is different when no unused hpas are found because of a difference in the JSON functions.
> 
> output for no unused hpas is:
> 
> ```json
> {}
> ```
> 
> all other resources when there none unused return something like:
> 
> ```json
> {
>   "kor": {
>     "Deployments": null
>   }
> }
> ```
> 
> refactoring the json outputs to one standard should probably be discussed in a different issue.

Hmm this is kind of a bug. 
This should definitely be aligned

**Comment by yonahd** [comment]
I'll open an issue to align the json responses

**Comment by yonahd** [comment]
> I can also add `fmt.Fprintf(os.Stderr, "Failed to process namespace %s: %v\n", namespace, err)` to the cmd functions for better formatting. @yonahd update me on what you think.

You mean the tabular response command?

**Comment by yonahd** [comment]
> @Yuni-sa would you like to add this to the MR or should I leave it as a separate issue? #44

Keeping as separate issue

**Comment by Yuni-sa** [comment]
> I'll open an issue to align the json responses

as this got closed by #39 

> @Yuni-sa would you like to add this to the MR or should I leave it as a separate issue? #44

and this is being handled by #44

@yonahd anything more I should fix/add for this pr to be reviewed and merged?

**Pull request merged**
