### PR TITLE
feat: add helm chart testing

### PR DESCRIPTION
**Pull request by found-it**
Add helm chart testing with https://github.com/helm/chart-testing-action

## What this PR does / why we need it?

This PR adds some basic helm chart testing. It lints the chart and spins up a cluster to install the chart with each values file in `charts/kor/ci/*-values.yaml`.

## PR Checklist

- [ ] This PR adds K8s exceptions (false positives)
- [ ] This PR adds new code
- [ ] This PR includes tests for new/existing code
- [ ] This PR adds docs
- [x] This PR add helm chart tests

## GitHub Issue

Should address https://github.com/yonahd/kor/issues/286

## Notes for your reviewers

I just took the basic example from https://github.com/helm/chart-testing-action and applied it here. I ran `ct install` locally to test the chart, it correctly failed without the fixes from https://github.com/yonahd/kor/pull/292 and correctly passed when I applied the fixes.

I just set up default and "with cronjob" values since those are the two documented cases in the README.

I also had to modify the `.gitignore` because the `kor` entry was too broad and ended up ignoring things in `charts/kor`

### CODE REVIEW

**Comment by yonahd** [comment]
Looks like you need to bump the chart version
And then regenerate the Readme using
`docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest `

**Comment by yonahd** [comment]
Looks good.
Just regenerate the helm Readme using
docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest

**Comment by found-it** [comment]
@yonahd I added a test to CI to alert when the readme needs to be regenerated. I just want to test and make sure it does the right thing then I will update the readme and add

**Comment by found-it** [comment]
Awesome, looks like it did the right thing. Updated the readme

**Comment by yonahd** [comment]
> @yonahd I added a test to CI to alert when the readme needs to be regenerated. I just want to test and make sure it does the right thing then I will update the readme and add

Nice!
Looks like you also did most of #287

**Review by yonahd — APPROVED** [review]
LGTM
Thank you!

**Pull request merged**
